env:
    es6: true
    node: true
    screeps/screeps: true
extends: 'eslint:recommended'
globals:
    Atomics: readonly
    SharedArrayBuffer: readonly
parserOptions:
    ecmaVersion: 2018
    sourceType: module
plugins:
    - screeps
ignorePatterns:
    - 'dist/'
    - 'node_modules/'
rules: {}
